name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Set permissions for GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace secrets in config.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Debug: Check if secrets are available
          echo "Replacing placeholders in config.js..."
          echo "SUPABASE_URL length: ${#SUPABASE_URL}"
          echo "SUPABASE_ANON_KEY length: ${#SUPABASE_ANON_KEY}"
          
          # Use environment variables with proper escaping
          sed -i "s|'REPLACE_SUPABASE_URL'|'${SUPABASE_URL}'|g" config.js
          sed -i "s|'REPLACE_SUPABASE_ANON_KEY'|'${SUPABASE_ANON_KEY}'|g" config.js
          
          # Verify replacement worked
          echo "Checking if replacement was successful..."
          grep -n "REPLACE_" config.js || echo "No placeholders found - replacement successful!"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4