name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate config.js with API key
        run: |
          cat > config.js << EOF
          const CONFIG = {
            SUPABASE_URL: '${{ secrets.SUPABASE_URL }}',
            SUPABASE_ANON_KEY: '${{ secrets.SUPABASE_ANON_KEY }}',
            CRUISE_PASSWORD: "divas2025",
            CRUISE_DATE: new Date("October 6, 2025 15:30:00")
          };
          window.CRUISE_CONFIG = CONFIG;
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: .
          publish_dir: .
